version: '3'
services:
  mongodb:
    image: mongo
    platform: linux/arm64
    ports:
      - 27017:27017

  redis:
    image: redis
    platform: linux/arm64
    ports:
      - 6379:6379

  app:
    build: .
    platform: linux/arm64
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - redis